# Generated by Django 4.0.5 on 2022-08-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_search_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='search',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
